apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.demo-app: semver:~1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: shivamg202/demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
